"""add last_active to users and index quiz_results user_id

Revision ID: 45578a337f78
Revises: 9421a2f239a5
Create Date: 2026-05-10 11:13:43.927313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45578a337f78'
down_revision = '9421a2f239a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_results_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('registered_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_users', schema=None) as batch_op:
        batch_op.drop_column('last_active')

    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_results_user_id'))

    # ### end Alembic commands ###
