"""add user_achievements table

Revision ID: f3a8b2c91d45
Revises: 45578a337f78
Create Date: 2026-05-10 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f3a8b2c91d45"
down_revision = "45578a337f78"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_achievements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("achievement_key", sa.String(), nullable=False),
        sa.Column("earned_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["registered_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_achievements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_achievements_user_id"), ["user_id"], unique=False
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_achievements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_achievements_user_id"))
    op.drop_table("user_achievements")
    # ### end Alembic commands ###
